set(CMAKE_SYSTEM_NAME Windows)

if(NOT DEFINED HKM_MINGW_ROOT OR HKM_MINGW_ROOT STREQUAL "")
    message(FATAL_ERROR "HKM_MINGW_ROOT must point to the MinGW toolchain root, for example D:/Qt/Tools/mingw1310_64.")
endif()

file(TO_CMAKE_PATH "${HKM_MINGW_ROOT}" HKM_MINGW_ROOT)
set(HKM_MINGW_ROOT "${HKM_MINGW_ROOT}" CACHE PATH "MinGW toolchain root")
if(DEFINED HKM_MINGW_TRIPLET AND NOT HKM_MINGW_TRIPLET STREQUAL "")
    set(HKM_MINGW_TRIPLET "${HKM_MINGW_TRIPLET}" CACHE STRING "Optional MinGW target triplet, for example i686-w64-mingw32.")
else()
    set(HKM_MINGW_TRIPLET "" CACHE STRING "Optional MinGW target triplet, for example i686-w64-mingw32.")
endif()
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES HKM_MINGW_ROOT HKM_MINGW_TRIPLET)

function(hkm_find_mingw_tool out_var tool_name)
    if(NOT HKM_MINGW_TRIPLET STREQUAL "" AND EXISTS "${HKM_MINGW_ROOT}/bin/${HKM_MINGW_TRIPLET}-${tool_name}.exe")
        set(${out_var} "${HKM_MINGW_ROOT}/bin/${HKM_MINGW_TRIPLET}-${tool_name}.exe" PARENT_SCOPE)
    elseif(EXISTS "${HKM_MINGW_ROOT}/bin/${tool_name}.exe")
        set(${out_var} "${HKM_MINGW_ROOT}/bin/${tool_name}.exe" PARENT_SCOPE)
    else()
        message(FATAL_ERROR "Unable to locate ${tool_name}.exe in ${HKM_MINGW_ROOT}/bin.")
    endif()
endfunction()

hkm_find_mingw_tool(HKM_MINGW_CC gcc)
hkm_find_mingw_tool(HKM_MINGW_CXX g++)
hkm_find_mingw_tool(HKM_MINGW_RC windres)
hkm_find_mingw_tool(HKM_MINGW_AR ar)
hkm_find_mingw_tool(HKM_MINGW_RANLIB ranlib)

set(CMAKE_C_COMPILER "${HKM_MINGW_CC}" CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER "${HKM_MINGW_CXX}" CACHE FILEPATH "")
set(CMAKE_RC_COMPILER "${HKM_MINGW_RC}" CACHE FILEPATH "")
set(CMAKE_AR "${HKM_MINGW_AR}" CACHE FILEPATH "")
set(CMAKE_RANLIB "${HKM_MINGW_RANLIB}" CACHE FILEPATH "")

if(CMAKE_GENERATOR MATCHES "Ninja" AND EXISTS "D:/Qt/Tools/Ninja/ninja.exe")
    set(CMAKE_MAKE_PROGRAM "D:/Qt/Tools/Ninja/ninja.exe" CACHE FILEPATH "Ninja executable")
elseif(CMAKE_GENERATOR STREQUAL "MinGW Makefiles")
    set(CMAKE_MAKE_PROGRAM "${HKM_MINGW_ROOT}/bin/mingw32-make.exe" CACHE FILEPATH "MinGW make executable")
endif()
