#pragma once

#include "HotkeyTypes.h"

#include <QString>

namespace UiText {

enum class Key {
    SearchPlaceholder,
    Settings,
    Minimize,
    Close,
    HotkeysEnabled,
    UpdatesEnabled,
    CheckForUpdates,
    UpdateChecking,
    UpdateAvailableTitle,
    UpdateAvailableMessage,
    UpdateNotAvailable,
    UpdateFailed,
    OpenDownloadPage,
    Language,
    Theme,
    ThemeSystem,
    ThemeLight,
    ThemeDark,
    ItemAppearance,
    SectionAppearance,
    CategoryAppearance,
    HotkeyList,
    HotkeyListEmpty,
    HotkeyListCategory,
    HotkeyListItem,
    HotkeyListHotkey,
    HotkeyListTarget,
    SectionHeight,
    CategoryHeight,
    IconWidth,
    IconHeight,
    ItemWidth,
    ItemHeight,
    FontFamily,
    FontPointSize,
    TextColor,
    DefaultColor,
    ChooseColor,
    HorizontalSpacing,
    VerticalSpacing,
    MultilineText,
    ShowEllipsis,
    Chinese,
    English,
    Ok,
    Cancel,
    Yes,
    No,
    OpenMainWindow,
    Exit,
    NewSection,
    EditSection,
    DeleteSection,
    EncryptSection,
    UnlockSection,
    AddItem,
    Run,
    RunAsAdmin,
    ExplorerContextMenu,
    BrowseTarget,
    CreateDesktopShortcut,
    SetStartup,
    Edit,
    Delete,
    LockedHint,
    UnboundHotkey,
    Disabled,
    EncryptedItemCount,
    ItemCount,
    HotkeyHookFailed,
    HookRunning,
    HotkeysPaused,
    HotkeysResumed,
    SectionLockedCancelled,
    LaunchFailed,
    Launched,
    SaveFailed,
    SavedItems,
    NewSectionTitle,
    EditSectionTitle,
    Name,
    IconKey,
    SortOrder,
    InvalidSection,
    SectionNameRequired,
    DeleteSectionTitle,
    DeleteSectionWithItems,
    DeleteSectionConfirm,
    EncryptSectionTitle,
    EncryptSectionPrompt,
    InvalidItem,
    ItemTargetRequired,
    HotkeyWarning,
    HotkeyDuplicateWarning,
    HotkeySystemShortcutWarning,
    HotkeyCheck,
    HotkeyCheckInvalid,
    HotkeyCheckAvailable,
    HotkeyCheckSystemReserved,
    HotkeyCheckRegisteredByOtherApp,
    HotkeyCheckBestEffort,
    HotkeyCheckCannotForceDisable,
    HotkeyCheckWindowsOnly,
    DeleteItemTitle,
    DeleteItemConfirm,
    UnlockSectionTitle,
    UnlockSectionPrompt,
    WrongPasswordTitle,
    WrongPasswordMessage,
    EnabledCount,
    CategoryProgram,
    CategoryFolder,
    CategoryWebsite,
    SectionSystemTools,
    SectionMyPrograms,
    SectionSystemFolders,
    SectionMyFolders,
    SectionCommonWebsites,
    SectionMyWebsites,
    RuleDialogProgramTitle,
    RuleDialogFolderTitle,
    RuleDialogWebsiteTitle,
    Description,
    Target,
    Arguments,
    WorkingDirectory,
    Hotkey,
    Record,
    Browse,
    SelectFolder,
    SelectProgram,
    ProgramTargetPlaceholder,
    FolderTargetPlaceholder,
    WebsiteTargetPlaceholder,
    DescriptionPlaceholder,
    ArgumentsPlaceholder,
    WorkingDirectoryPlaceholder,
    HotkeyPlaceholder,
    TrayTooltip,
    SystemTrayUnavailable
};

QString normalizeLanguage(const QString& language);
QString text(const QString& language, Key key);
QString categoryName(const QString& language, LauncherCategory category);

} // namespace UiText
